
export const cararr = [
    {
      imgsrc: 'https://cdn.bigboytoyz.com/new-version/products/jaguar-xjl-portfolio-bbt-2022071.jpg',
      description: 'Jaguar is the luxury vehicle brand of Jaguar Land Rover, a British multinational car manufacturer with its headquarters in Whitley, Coventry, England.',
      modelName: 'XL',
      year: 2020,
      listPrice: 10000000,
      colors: ['BLACK', 'BLUE'],
      mileage: 6,
      power: 400,
      maxSpeed: 250,
    },
    {
      imgsrc: 'https://images.unsplash.com/photo-1532974297617-c0f05fe48bff?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxleHBsb3JlLWZlZWR8Mnx8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=60',
      description: 'The Audi A8 is a four-door, full-size, luxury sedan manufactured and marketed by the German automaker Audi. Succeeding the Audi V8, and now in its fourth generation, the A8 has been offered with both front- or permanent all-wheel drive—and in short- and long-wheelbase variants.',
      modelName: 'A8 L 60 TFSI quattro',
      year: 2021,
      listPrice: 9000000,
      colors: ['BLACK', 'WHITE', 'GREY', 'BLUE'],
      mileage: 10,
      power: 600,
      maxSpeed: 250,
    },
    {
      imgsrc: 'https://images.unsplash.com/photo-1547038577-da80abbc4f19?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxleHBsb3JlLWZlZWR8NXx8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=60',
      description: 'The Mercedes-Benz S-Class, formerly known as Sonderklasse (German for "special class", abbreviated as "S-Klasse"), is a series of full-size luxury sedans, limousines and armored sedans produced by the German automaker Mercedes-Benz, a division of German company Daimler AG.',
      modelName: 'S-Class',
      year: 2022,
      listPrice: 12000000,
      colors: ['BLACK', 'SILVER', 'BLUE', 'RED'],
      mileage: 8,
      power: 550,
      maxSpeed: 250,
    },
    {
      imgsrc: 'https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxleHBsb3JlLWZlZWR8OXx8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=60',
      description: 'The Lamborghini Aventador is a mid-engine sports car produced by the Italian automotive manufacturer Lamborghini. In keeping with Lamborghini tradition, the Aventador is named after a fighting bull. Aventador S is an updated version of the Aventador, with improvements to handling and performance.',
      modelName: 'Aventador S',
      year: 2020,
      listPrice: 34000000,
      colors: ['YELLOW', 'GREEN', 'ORANGE'],
      mileage: 5,
      power: 730,
      maxSpeed: 217,
    },
    {
      imgsrc: 'https://images.unsplash.com/photo-1623006772851-a8bf2c47d304?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxleHBsb3JlLWZlZWR8MTd8fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=500&q=60',
      description: 'The Ferrari 812 Superfast is a front-engine, rear-wheel-drive grand tourer produced by Italian sports car manufacturer Ferrari that made its debut at the 2017 Geneva Motor Show. It is the successor to the F12berlinetta. The car has a 6.5-liter naturally aspirated V12 engine that produces 789 hp and 530 lb-ft of torque.',
      modelName: '812 Superfast',
      yearyear: 2020,
      listPrice: 48000000,
      colors: ['RED', 'YELLOW', 'BLACK'],
      mileage: 10,
      power: 789,
      maxSpeed: 211,
      },
      {
        imgsrc: 'https://images.unsplash.com/photo-1489686995744-f47e995ffe61?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxleHBsb3JlLWZlZWR8MjR8fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=500&q=60',
        description: 'The Rolls-Royce Phantom VIII is a full-sized luxury saloon manufactured by Rolls-Royce Motor Cars. It is the eighth and current generation of the Rolls-Royce Phantom, and the second launched by Rolls-Royce under BMW ownership.',
        modelName: 'Phantom VIII',
        year: 2021,
        listPrice: 18000000,
        colors: ['WHITE', 'SILVER', 'BLACK', 'GREY'],
        mileage: 7,
        power: 563,
        maxSpeed: 155,
        },
        {
        imgsrc: 'https://images.unsplash.com/photo-1604705528621-81b2755a320b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxleHBsb3JlLWZlZWR8Mjd8fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=500&q=60',
        description: 'The Aston Martin DB11 is a grand tourer produced by British luxury car manufacturer Aston Martin since 2016. It debuted at the Geneva Motor Show in March 2016, as a replacement to the DB9. The car is available in both coupe and convertible versions.',
        modelName: 'DB11',
        year: 2022,
        listPrice: 15000000,
        colors: ['BLACK', 'BLUE', 'RED', 'GREEN'],
        mileage: 9,
        power: 503,
        maxSpeed: 200,
        },
        {
        imgsrc: 'https://images.unsplash.com/photo-1609520505218-7421df70121d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxleHBsb3JlLWZlZWR8NDR8fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=500&q=60',
        description: 'The Bentley Flying Spur is a luxury car produced by Bentley Motors Limited since 2005. The car is available in two variants - the four-door sedan and the two-door coupe. The car features a W12 engine that produces up to 616 horsepower and 590 lb-ft of torque.',
        modelName: 'Flying Spur W12',
        year: 2022,
        listPrice: 22000000,
        colors: ['BLACK', 'BLUE', 'SILVER', 'WHITE'],
        mileage: 8,
        power: 616,
        maxSpeed: 200,
        },
        {
        imgsrc: 'https://images.unsplash.com/photo-1621252792374-2b79e3fcf295?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxleHBsb3JlLWZlZWR8NDd8fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=500&q=60',
        description: 'The Tesla Model X is a mid-size all-electric luxury SUV made by Tesla, Inc. The vehicle is notable for its falcon-wing doors, which open upwards allowing access to the second and third row seats. The car can seat up to 7 passengers and features a range of up to 340 miles on a single charge.',
        modelName: 'Model X P100D',
        year: 2021,
        listPrice: 15000000,
        colors: ['BLACK', 'WHITE', 'BLUE'],
        mileage: 295,
        power: 588,
        maxSpeed: 155,
        }]
  

